version: '3.8'

services:
    dev:
        container_name: athena_api_dev
        image: athena-api-dev:0.0.3
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3001:3001
            - 9229:9229
        networks:
            - athena-api
            - postgres
        links:
          - postgres:postgres
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - postgres

    prod:
        container_name: athena_api_prod
        image: athena-api-prod:0.0.3
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - athena-api
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

    postgres:
        image: postgres:alpine
        ports:
        - 5432:5432
        container_name: 'postgres-alpine'
        restart: always
        volumes:
        - pg-data:/var/lib/postgresql/data
        networks:
            - postgres
        environment:
            POSTGRES_USER: athena
            POSTGRES_PASSWORD: athena

networks:
    athena-api:
      name: athena-api
    postgres:
        driver: bridge

volumes:
  pg-data:
